
version: 2

models:
  - name: camel_stream
    description: "Starting model"
    columns:
      - name: login
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: firstname
        tests:
          - not_null
      - name: lastname
        tests:
          - not_null
      - name: startdate
        tests:
          - not_null
      - name: enddate
        tests:
          - not_null
